### ISSUE TITLE
Wrong priority for conj-verb rule

### ISSUE THREAD

**Issue by oscartackstrom** [sivareddyg/UDepLambda#11]
"Queen Elizabeth II married Philip Mountbatten, Duke of Edinburgh, in 1947, became queen on February 6, 1952, and was crowned on June 2, 1953."

gives

[["arg0(12:e , 12:m.1947)","arg0(20:e , 20:m.February_6_,_1952)","arg0(29:e , 29:m.June_2_,_1953)","arg0(2:e , 2:m.Elizabeth_II)","arg0(5:e , 5:m.Philip_Mountbatten)","arg0(9:e , 9:m.Edinburgh)","become.arg1(14:e , 2:m.Elizabeth_II)","become.nmod.in(14:e , 12:m.1947)","become.nmod.on(14:e , 20:m.February_6_,_1952)","crown.arg1(24:e , 2:m.Elizabeth_II)","crown.nmod.in(24:e , 12:m.1947)","crown.nmod.on(24:e , 29:m.June_2_,_1953)","duke(7:s , 5:m.Philip_Mountbatten)","marry.arg1(3:e , 2:m.Elizabeth_II)","marry.arg2(3:e , 5:m.Philip_Mountbatten)","marry.nmod.in(3:e , 12:m.1947)","nmod.of(5:e , 9:m.Edinburgh)","queen(0:s , 2:m.Elizabeth_II)"]]

where there are several spurious *nmod.in and *nmod.on predicates.

**Comment by sivareddyg** [comment]
Fixed: https://github.com/sivareddyg/UDepLambda/commit/5cf37c7c23f8818349ac0363ef26af8650f180f5

This solution no longer aims to handle adjunct extractions in VP constructions. Sacrificing recall for precision.

**Comment by sivareddyg** [comment]
Pretty happy with the final parse :)

["arg0(12:e , 12:m.1947)","arg0(20:e , 20:m.February_6_,_1952)","arg0(29:e , 29:m.June_2_,_1953)","arg0(2:e , 2:m.Elizabeth_II)","arg0(5:e , 5:m.Philip_Mountbatten)","arg0(9:e , 9:m.Edinburgh)","become.arg1(14:e , 2:m.Elizabeth_II)","become.arg2(14:e , 15:m.queen)","become.nmod.on(14:e , 20:m.February_6_,_1952)","crown.arg1(24:e , 2:m.Elizabeth_II)","crown.nmod.on(24:e , 29:m.June_2_,_1953)","duke(7:s , 5:m.Philip_Mountbatten)","marry.arg1(3:e , 2:m.Elizabeth_II)","marry.arg2(3:e , 5:m.Philip_Mountbatten)","marry.nmod.in(3:e , 12:m.1947)","nmod.of(5:e , 9:m.Edinburgh)","queen(0:s , 2:m.Elizabeth_II)"]
