### ISSUE TITLE
Can't download the Freebase version, link broken

### ISSUE THREAD

**Issue by Zhenshan-Jin** [sivareddyg/UDepLambda#16]
The link under [FreebaseExperiments.md](https://github.com/sivareddyg/UDepLambda/blob/master/doc/FreebaseExperiments.md) for Freebase version: https://www.dropbox.com/sh/zxv2mos2ujjyxnu/AAACCR4AJ1MMTCe8ElfBN39Ha?dl=0 seems broken with Dropbox error 429
![dropbox_error](https://user-images.githubusercontent.com/14370804/34234649-001ff384-e5b2-11e7-8e8a-5cd4bcc1e7de.png)

Thanks!
Zhenshan

**Comment by sivareddyg** [comment]
Hi Zhenshan,

I did not renew my dropbox subscription this year since it is expensive. This is a huge file. I have to find another way to share this redsource. Are you trying to run FB experiments? How urgently do you need this.

Cheers,
Siva

**Comment by Zhenshan-Jin** [comment]
Hi Siva,

Thanks for the quick reply! Yes, I'm trying to run FB experiments. I'm trying to build a freebase style question & answering system based on your paper result, which I believe would be promising. So

**Comment by Zhenshan-Jin** [comment]
One solution that I can come up with is that my Dropbox account has the subscription and will end at next July. If you think it's ok, you send me the file and I can help to put the file in my Dropbox account and share the link in your repo. What do you think of it?

**Comment by sivareddyg** [comment]
I renewed my subscription for a month. You can try downloading now. 

Another note: use virtuoso-6 instead of 7. http://sourceforge.net/projects/virtuoso/files/virtuoso/6.1.8/virtuoso-opensource-x64-20131211.zip/download The newer version is not compatible with my code and would be very slow.

**Comment by Zhenshan-Jin** [comment]
@sivareddyg thank you!

**Comment by hiroshinoji** [comment]
I was trying to reproduce the experiments and encountered the same issue. I wish I could access the file in some way... Do you have a plan to put the file in another place?

Thanks.

**Comment by sivareddyg** [comment]
Future reference: You can download a copy from https://drive.google.com/drive/folders/1UCFaUbjFYVI4Hwn1t40LBHJ3OMm66xsD?usp=sharing
