### ISSUE TITLE
Freebase dataset

### ISSUE THREAD

**Issue by hiroshinoji** [sivareddyg/UDepLambda#21]
The same as #16. Do you have a plan to distribute the Freebase dataset again? I wish I can access the data in some way.

Thanks.

**Comment by sivareddyg** [comment]
You can download a copy from https://drive.google.com/drive/folders/1UCFaUbjFYVI4Hwn1t40LBHJ3OMm66xsD?usp=sharing

**Comment by hiroshinoji** [comment]
Thank you very much!
