### ISSUE TITLE
SingleEvent Freebase Experiments Replication

### ISSUE THREAD

**Issue by sivareddyg** [sivareddyg/UDepLambda#9]
Hi Allan,

I updated the doc with preliminary guidelines https://github.com/sivareddyg/UDepLambda/blob/master/doc/FreebaseExperiments.md. 

I also gave you WebQuestions permission for English (sent through bitbucket). Let me know how this goes. I will post more updates later.

Siva

**Comment by allanj** [comment]
Thanks @sivareddyg I will work on this and try to figure how does one single model can be trained.
